/**
 * ArtistAPI2
 * ArtistAPI2
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Artist { 
    artistName?: string;
    artistGenre?: string;
    albumsRecorded?: number;
    username?: string;
}